version: '3.7'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: clientmysql
    environment:
      MYSQL_DATABASE: client_microservice
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      timeout: 1s
      retries: 5

  client_microservice:
    image: client_microservice
    container_name: client_microservice
    build:
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: clientmysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    ports:
      - 8500:8414
      - 5005:5005  # Expose debugging port
    depends_on:
       mysql:
         condition: service_healthy