package com.example.bvnk_client_service.api;

import com.example.bvnk_client_service.DTO.response.TransactionResponseData;
import feign.HeaderMap;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.Map;


/**
 * This interface defines the methods that the client can use to interact with the transaction service.
 * The interface is implemented by the Feign client, which is generated by Spring Cloud.
 * The client makes HTTP requests to the transaction service using the methods defined in this interface.
 */
@FeignClient(name = "transactionMicroservice", url = "${transactionMicroservice.url}")
public interface TransactionServiceAPI {

	/**
	 * This method is used to add a transaction for a specific client.
	 *
	 * @param headers The headers of the request
	 * @param clientId The ID of the client
	 * @param transactionId The ID of the transaction
	 *
	 * @return The response data of the transaction
	 */
	@PostMapping
	TransactionResponseData addTransactionForClient(@HeaderMap Map<String, Object> headers,
													@RequestParam String clientId,
													@RequestParam String transactionId);

}
